apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapi
spec:
  selector:
    matchLabels:
      app: helloapi
  replicas: 2
  template:
    metadata:
      labels:
        app: helloapi
    spec:
      containers:
        - name: helloapi
          image: helloapi:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
