create table employees (id bigint generated by default as identity, email_id varchar(255), first_name varchar(255),
last_name varchar(255), primary key (id));
INSERT INTO employees (id, first_name, last_name, email_id) VALUES (1, 'Zalumabo', 'Ndaba', 'zalu.ndaba@gmail.com');
INSERT INTO employees (id, first_name, last_name, email_id) VALUES (2, 'Sboniso', 'Ndaba', 'sboniso.ndaba@gmail.com');